name: Protect main branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-source:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" != "test" ]]; then
            echo "Only 'test' branch can merge into main."
            exit 1
          fi
